[project]
name = "flaskr"
version = "1.0.0"
description = "SocialMiner 1.0.0, Una herramienta para la realización de raspado de datos en X."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
