name: Build and push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURECREDENTIALS }}

      - name: Docker login to Azure Container Registry
        run: az acr login --name socialminerapp

      - name: Check Dockerfile exists
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile not found!"
            exit 1
          fi

      - name: Build & Push Docker image
        run: |
          docker build -t socialminerapp.azurecr.io/testdocker:latest .
          docker push socialminerapp.azurecr.io/testdocker:latest
